// <auto-generated />
using System;
using Exam2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exam2.Migrations
{
    [DbContext(typeof(Exam2Context))]
    [Migration("20181214193112_secondmigration")]
    partial class secondmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Exam2.Models.Activities", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreatorId");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<int>("Duration");

                    b.Property<string>("DurationUnit");

                    b.Property<string>("Title");

                    b.HasKey("ActivitiesId");

                    b.HasIndex("CreatorId");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Exam2.Models.Participants", b =>
                {
                    b.Property<int>("ParticipantsId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivitiesId");

                    b.Property<int>("UsersId");

                    b.HasKey("ParticipantsId");

                    b.HasIndex("ActivitiesId");

                    b.HasIndex("UsersId");

                    b.ToTable("participants");
                });

            modelBuilder.Entity("Exam2.Models.Users", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UsersId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Exam2.Models.Activities", b =>
                {
                    b.HasOne("Exam2.Models.Users", "Creator")
                        .WithMany("Activities")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Exam2.Models.Participants", b =>
                {
                    b.HasOne("Exam2.Models.Activities", "Activity")
                        .WithMany("Participants")
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Exam2.Models.Users", "User")
                        .WithMany("Participating")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
